---
- name: install packages
  ansible.builtin.shell: |
    set -euo pipefail
    apm list --bare | grep -E '^{{ item }}@' &&
    echo 'Already installed.' ||
    apm install '{{ item }}'
  args:
    executable: /bin/bash
  with_items:
    - "{{ atom_packages }}"
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"
